-- MySQL Script generated by MySQL Workbench
-- Mon Dec 12 15:44:03 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema chimedb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema chimedb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `chimedb` DEFAULT CHARACTER SET utf8 ;
USE `chimedb` ;

-- -----------------------------------------------------
-- Table `chimedb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chimedb`.`user` (
  `userID` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`userID`),
  UNIQUE INDEX `userID_UNIQUE` (`userID` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `chimedb`.`admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chimedb`.`admin` (
  `adminID` INT NOT NULL,
  `adminName` VARCHAR(45) NULL,
  PRIMARY KEY (`adminID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chimedb`.`store`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chimedb`.`store` (
  `storeID` INT NOT NULL AUTO_INCREMENT,
  `storeName` VARCHAR(45) NULL,
  `adminID` INT NULL,
  PRIMARY KEY (`storeID`),
  INDEX `adminID_idx` (`adminID` ASC) VISIBLE,
  CONSTRAINT `adminID`
    FOREIGN KEY (`adminID`)
    REFERENCES `chimedb`.`admin` (`adminID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chimedb`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chimedb`.`product` (
  `productID` INT NOT NULL AUTO_INCREMENT,
  `productName` VARCHAR(45) NULL,
  `storeID` INT NULL,
  PRIMARY KEY (`productID`),
  INDEX `storeID_idx` (`storeID` ASC) VISIBLE,
  CONSTRAINT `storeID`
    FOREIGN KEY (`storeID`)
    REFERENCES `chimedb`.`store` (`storeID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chimedb`.`script`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chimedb`.`script` (
  `scriptID` INT NOT NULL,
  `scriptText` TEXT NULL,
  `productID` INT NULL,
  PRIMARY KEY (`scriptID`),
  INDEX `productID_idx` (`productID` ASC) VISIBLE,
  CONSTRAINT `productIDphoneNumber`
    FOREIGN KEY (`productID`)
    REFERENCES `chimedb`.`product` (`productID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chimedb`.`hashtag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chimedb`.`hashtag` (
  `hashtagID` INT NOT NULL AUTO_INCREMENT,
  `hashtagText` VARCHAR(45) NULL,
  `sentAmount` VARCHAR(45) NULL,
  `scriptID` INT NULL,
  PRIMARY KEY (`hashtagID`),
  INDEX `scriptID_idx` (`scriptID` ASC) VISIBLE,
  CONSTRAINT `scriptID`
    FOREIGN KEY (`scriptID`)
    REFERENCES `chimedb`.`script` (`scriptID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chimedb`.`phone_number`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chimedb`.`phone_number` (
  `phoneNumberID` INT NOT NULL AUTO_INCREMENT,
  `phoneNumber` VARCHAR(20) NULL,
  `dateSend` DATETIME NULL,
  `served` TINYINT NULL,
  `sendBy` VARCHAR(45) NULL,
  `productID` INT NULL,
  PRIMARY KEY (`phoneNumberID`),
  INDEX `sendBy_idx` (`sendBy` ASC) VISIBLE,
  INDEX `productID_idx` (`productID` ASC) VISIBLE,
  CONSTRAINT `sendBy`
    FOREIGN KEY (`sendBy`)
    REFERENCES `chimedb`.`user` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `productID`
    FOREIGN KEY (`productID`)
    REFERENCES `chimedb`.`product` (`productID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chimedb`.`list_data`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chimedb`.`list_data` (
  `listDataID` INT NOT NULL AUTO_INCREMENT,
  `haveDone` TINYINT NULL,
  `onDate` DATE NULL,
  `phoneNumberID` INT NULL,
  `forUser` VARCHAR(45) NULL,
  PRIMARY KEY (`listDataID`),
  INDEX `phoneNumberID_idx` (`phoneNumberID` ASC) VISIBLE,
  INDEX `forUser_idx` (`forUser` ASC) VISIBLE,
  CONSTRAINT `phoneNumberID`
    FOREIGN KEY (`phoneNumberID`)
    REFERENCES `chimedb`.`phone_number` (`phoneNumberID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `forUser`
    FOREIGN KEY (`forUser`)
    REFERENCES `chimedb`.`user` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
